run_name: TNG300-1_1024
snapshot_directory: /tigress/TNG/300-1-Dark/
snapfile_root: 99
num_snaps: 4
output_directory: /tigress/TNG/300-1-Dark/out/
xmin: 0.0
xmax: 205000.0
num_scales: 10
nx: 1024
algorithm: NEXUS
number_subboxes: 2
subbox_buffer: 64